remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: XSYS Arena
description: Because balance is overrated.
show_downloads: false
excerpt_separator: <!--more-->
author: XSYS Team
